export const queryKeys = {
  currentUser: ['session', 'current-user'] as const,
  cart: ['customer', 'cart'] as const,
  addresses: ['customer', 'addresses'] as const,
  favorites: ['customer', 'favorites'] as const,
  favoritesAll: ['customer', 'favorites', 'all'] as const,
  favoritesPage: (page: number, size: number) => ['customer', 'favorites', 'page', { page, size }] as const,
  order: (orderId: string) => ['customer', 'orders', orderId] as const,
  orders: (page: number, status?: string) => ['customer', 'orders', 'list', { page, status: status ?? null }] as const,
  notifications: (page: number, read?: boolean) => ['customer', 'notifications', { page, read: read ?? null }] as const,
  notificationBadge: ['customer', 'notifications', 'unread-count'] as const,
  review: (orderId: string) => ['customer', 'reviews', orderId] as const,
  publicReviews: (restaurantId: string, page: number) => ['discovery', 'restaurants', restaurantId, 'reviews', page] as const,
  zones: ['discovery', 'delivery-zones'] as const,
  restaurantContext: ['restaurant-operations', 'context'] as const,
  restaurant: (restaurantId: string) => ['restaurant-operations', restaurantId, 'restaurant'] as const,
  branches: (restaurantId: string) => ['restaurant-operations', restaurantId, 'branches'] as const,
  branchHours: (restaurantId: string, branchId: string) => ['restaurant-operations', restaurantId, 'branches', branchId, 'hours'] as const,
  menu: (restaurantId: string) => ['restaurant-operations', restaurantId, 'menu'] as const,
  categories: (restaurantId: string) => ['restaurant-operations', restaurantId, 'menu', 'categories'] as const,
  items: (restaurantId: string, categoryId: string) => ['restaurant-operations', restaurantId, 'menu', 'categories', categoryId, 'items'] as const,
  branchOverrides: (restaurantId: string, branchId: string) => ['restaurant-operations', restaurantId, 'branches', branchId, 'menu-overrides'] as const,
  deliveryRules: (restaurantId: string, branchId: string) => ['restaurant-operations', restaurantId, 'branches', branchId, 'delivery-rules'] as const,
  staff: (restaurantId: string) => ['restaurant-operations', restaurantId, 'staff'] as const,
  restaurantOrders: (restaurantId: string, branchId: string | null, status: string | null, page: number) => ['restaurant-operations', restaurantId, 'orders', { branchId, status, page }] as const,
  restaurantOrder: (restaurantId: string, orderId: string) => ['restaurant-operations', restaurantId, 'orders', orderId] as const,
  restaurantApplications: ['customer', 'restaurant-applications'] as const,
  driverProfile: ['driver-operations', 'profile'] as const,
  driverOrders: ['driver-operations', 'orders', 'active'] as const,
  driverOrder: (orderId: string) => ['driver-operations', 'orders', orderId] as const,
  adminUsers: (filters: object) => ['admin', 'users', 'list', filters] as const,
  adminUser: (id: string) => ['admin', 'users', 'detail', id] as const,
  adminRestaurants: (filters: object) => ['admin', 'restaurants', 'list', filters] as const,
  adminRestaurant: (id: string) => ['admin', 'restaurants', 'detail', id] as const,
  adminRestaurantHistory: (id: string, page: number) => ['admin', 'restaurants', 'detail', id, 'history', page] as const,
  adminApplications: (status: string, page: number) => ['admin', 'applications', 'list', { status, page }] as const,
  adminApplication: (id: string) => ['admin', 'applications', 'detail', id] as const,
  adminApplicationSubmissions: (id: string, page: number) => ['admin', 'applications', 'detail', id, 'submissions', page] as const,
  adminApplicationDecisions: (id: string, page: number) => ['admin', 'applications', 'detail', id, 'decisions', page] as const,
  adminOrders: (filters: object) => ['admin', 'orders', 'list', filters] as const,
  adminOrder: (id: string) => ['admin', 'orders', 'detail', id] as const,
  adminDrivers: (filters: object) => ['admin', 'drivers', 'list', filters] as const,
  adminDriver: (id: string) => ['admin', 'drivers', 'detail', id] as const,
  adminAudit: (filters: object) => ['admin', 'audit', 'list', filters] as const,
}
