export const queryKeys = {
  currentUser: ['session', 'current-user'] as const,
  cart: ['customer', 'cart'] as const,
  addresses: ['customer', 'addresses'] as const,
  favorites: ['customer', 'favorites'] as const,
  favoritesAll: ['customer', 'favorites', 'all'] as const,
  favoritesPage: (page: number, size: number) => ['customer', 'favorites', 'page', { page, size }] as const,
  order: (orderId: string) => ['customer', 'orders', orderId] as const,
  orders: (page: number, status?: string) => ['customer', 'orders', 'list', { page, status: status ?? null }] as const,
  notifications: (page: number, read?: boolean) => ['customer', 'notifications', { page, read: read ?? null }] as const,
  notificationBadge: ['customer', 'notifications', 'unread-count'] as const,
  review: (orderId: string) => ['customer', 'reviews', orderId] as const,
  publicReviews: (restaurantId: string, page: number) => ['discovery', 'restaurants', restaurantId, 'reviews', page] as const,
  zones: ['discovery', 'delivery-zones'] as const,
  restaurantContext: ['restaurant-operations', 'context'] as const,
  restaurant: (restaurantId: string) => ['restaurant-operations', restaurantId, 'restaurant'] as const,
  branches: (restaurantId: string) => ['restaurant-operations', restaurantId, 'branches'] as const,
  branchHours: (restaurantId: string, branchId: string) => ['restaurant-operations', restaurantId, 'branches', branchId, 'hours'] as const,
  menu: (restaurantId: string) => ['restaurant-operations', restaurantId, 'menu'] as const,
  categories: (restaurantId: string) => ['restaurant-operations', restaurantId, 'menu', 'categories'] as const,
  items: (restaurantId: string, categoryId: string) => ['restaurant-operations', restaurantId, 'menu', 'categories', categoryId, 'items'] as const,
  branchOverrides: (restaurantId: string, branchId: string) => ['restaurant-operations', restaurantId, 'branches', branchId, 'menu-overrides'] as const,
  deliveryRules: (restaurantId: string, branchId: string) => ['restaurant-operations', restaurantId, 'branches', branchId, 'delivery-rules'] as const,
  staff: (restaurantId: string) => ['restaurant-operations', restaurantId, 'staff'] as const,
  restaurantOrders: (restaurantId: string, branchId: string | null, status: string | null, page: number) => ['restaurant-operations', restaurantId, 'orders', { branchId, status, page }] as const,
  restaurantOrder: (restaurantId: string, orderId: string) => ['restaurant-operations', restaurantId, 'orders', orderId] as const,
  restaurantApplications: ['customer', 'restaurant-applications'] as const,
}
