import { useState } from 'react'
import { useMutation, useQueries, useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { restaurantOperationsApi } from '../api/restaurantOperations'
import { queryKeys } from '../api/queryKeys'
import { formatMoney } from '../utils/money'
import { useRestaurantContext } from './RestaurantContext'
import { MutationMessage, PageHeader, Panel, Status } from './shared'
import type { ManagedCategory, ManagedItem } from '../api/contracts'

const categorySchema = z.object({ name: z.string().trim().min(1).max(120), description: z.string().max(2000) })
const itemSchema = z.object({ name: z.string().trim().min(1).max(120), description: z.string().max(2000), basePrice: z.string().regex(/^\d{1,10}(\.\d{1,2})?$/, 'Use a non-negative amount with up to 2 decimals'), available: z.boolean() })
type CategoryForm = z.infer<typeof categorySchema>
type ItemForm = z.infer<typeof itemSchema>

export function MenuManagementPage() {
  const { selected } = useRestaurantContext()
  const client = useQueryClient()
  const menu = useQuery({ queryKey: queryKeys.menu(selected.restaurantId), queryFn: () => restaurantOperationsApi.menu(selected.restaurantId), retry: false })
  const categories = useQuery({ queryKey: queryKeys.categories(selected.restaurantId), queryFn: () => restaurantOperationsApi.categories(selected.restaurantId), enabled: menu.isSuccess })
  const itemQueries = useQueries({ queries: (categories.data?.items ?? []).map((category) => ({ queryKey: queryKeys.items(selected.restaurantId, category.id), queryFn: () => restaurantOperationsApi.items(selected.restaurantId, category.id) })) })
  const [categoryId, setCategoryId] = useState('')
  const [editingCategory, setEditingCategory] = useState<{ category: ManagedCategory; version: number } | null>(null)
  const [editingItem, setEditingItem] = useState<{ item: ManagedItem; version: number } | null>(null)
  const categoryForm = useForm<CategoryForm>({ resolver: zodResolver(categorySchema), defaultValues: { name: '', description: '' } })
  const itemForm = useForm<ItemForm>({ resolver: zodResolver(itemSchema), defaultValues: { name: '', description: '', basePrice: '', available: true } })
  const createMenu = useMutation({ mutationFn: () => restaurantOperationsApi.createMenu(selected.restaurantId, `${selected.restaurantName} menu`), onSuccess: () => void client.invalidateQueries({ queryKey: queryKeys.menu(selected.restaurantId) }) })
  const addCategory = useMutation({ mutationFn: (value: CategoryForm) => editingCategory ? restaurantOperationsApi.updateCategory(selected.restaurantId, editingCategory.category.id, { ...value, active: editingCategory.category.active, version: editingCategory.version }) : restaurantOperationsApi.createCategory(selected.restaurantId, { ...value, version: categories.data!.version }), onSuccess: () => { setEditingCategory(null); categoryForm.reset(); void client.invalidateQueries({ queryKey: queryKeys.categories(selected.restaurantId) }) }, onError: (error) => { if ((error as { status?: number }).status === 409) void categories.refetch() } })
  const addItem = useMutation({ mutationFn: (value: ItemForm) => editingItem ? restaurantOperationsApi.updateItem(selected.restaurantId, editingItem.item.id, { ...value, active: editingItem.item.active, version: editingItem.version }) : restaurantOperationsApi.createItem(selected.restaurantId, categoryId, { ...value, version: itemQueries.find((_, index) => categories.data?.items[index]?.id === categoryId)?.data?.version ?? 0 }), onSuccess: () => { setEditingItem(null); itemForm.reset(); void client.invalidateQueries({ queryKey: queryKeys.items(selected.restaurantId, categoryId) }); void client.invalidateQueries({ queryKey: ['restaurant-operations', selected.restaurantId, 'branches'] }) } })
  const reorderCategories = useMutation({ mutationFn: ({ ids, version }: { ids: string[]; version: number }) => restaurantOperationsApi.reorderCategories(selected.restaurantId, ids, version), onSuccess: () => void client.invalidateQueries({ queryKey: queryKeys.categories(selected.restaurantId) }) })
  const reorderItems = useMutation({ mutationFn: ({ category, ids, version }: { category: string; ids: string[]; version: number }) => restaurantOperationsApi.reorderItems(selected.restaurantId, category, ids, version), onSuccess: (_, value) => void client.invalidateQueries({ queryKey: queryKeys.items(selected.restaurantId, value.category) }) })
  const move = (ids: string[], index: number, delta: number) => { const result = [...ids]; const target = index + delta; if (target < 0 || target >= result.length) return ids; [result[index], result[target]] = [result[target], result[index]]; return result }
  const beginCategoryEdit = async (category: ManagedCategory) => { const snapshot = await restaurantOperationsApi.category(selected.restaurantId, category.id); setEditingCategory({ category: snapshot.data, version: snapshot.version }); categoryForm.reset({ name: snapshot.data.name, description: snapshot.data.description ?? '' }) }
  const beginItemEdit = async (item: ManagedItem) => { const snapshot = await restaurantOperationsApi.item(selected.restaurantId, item.id); setCategoryId(item.categoryId); setEditingItem({ item: snapshot.data, version: snapshot.version }); itemForm.reset({ name: snapshot.data.name, description: snapshot.data.description ?? '', basePrice: String(snapshot.data.basePrice), available: snapshot.data.available }) }
  if (menu.isPending) return <><PageHeader title="Menu" /><Panel>Loading menu…</Panel></>
  if (menu.isError) return <><PageHeader eyebrow="Owner workspace" title="Menu" description="Create the restaurant menu before adding categories and items." /><Panel><MutationMessage error={createMenu.error} /><button className="primary-button" onClick={() => createMenu.mutate()} disabled={createMenu.isPending}>{createMenu.isPending ? 'Creating…' : 'Create menu'}</button></Panel></>
  return <><PageHeader eyebrow="Owner workspace" title={menu.data.name} description="Restaurant defaults are managed here. Branch-specific values stay visibly separate below." />
    <div className="ops-split"><Panel title={editingCategory ? 'Edit category' : 'Add category'}><form className="ops-form" onSubmit={categoryForm.handleSubmit((value) => addCategory.mutate(value))}><label>Name<input {...categoryForm.register('name')} /></label><label>Description<textarea rows={3} {...categoryForm.register('description')} /></label><MutationMessage error={addCategory.error} /><button className="primary-button">{editingCategory ? 'Save category' : 'Add category'}</button>{editingCategory && <button type="button" onClick={() => { setEditingCategory(null); categoryForm.reset() }}>Cancel</button>}</form></Panel>
    <Panel title={editingItem ? 'Edit menu item' : 'Add menu item'}><form className="ops-form" onSubmit={itemForm.handleSubmit((value) => addItem.mutate(value))}><label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required disabled={Boolean(editingItem)}><option value="">Choose category</option>{categories.data?.items.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Name<input {...itemForm.register('name')} /></label><label>Description<textarea rows={2} {...itemForm.register('description')} /></label><label>Base price (EGP)<input inputMode="decimal" {...itemForm.register('basePrice')} /></label><label className="check-label"><input type="checkbox" {...itemForm.register('available')} /> Available by default</label><MutationMessage error={addItem.error} /><button className="primary-button" disabled={!categoryId}>{editingItem ? 'Save item' : 'Add item'}</button>{editingItem && <button type="button" onClick={() => { setEditingItem(null); itemForm.reset() }}>Cancel</button>}</form></Panel></div>
    <div className="ops-card-list">{categories.data?.items.map((category, index) => <Panel key={category.id} title={category.name} actions={<div className="ops-row-actions"><Status value={category.active ? 'ACTIVE' : 'INACTIVE'} /><button onClick={() => void beginCategoryEdit(category)}>Edit</button><button disabled={index === 0} onClick={() => reorderCategories.mutate({ ids: move(categories.data!.items.map((item) => item.id), index, -1), version: categories.data!.version })}>Move up</button><button disabled={index === categories.data!.items.length - 1} onClick={() => reorderCategories.mutate({ ids: move(categories.data!.items.map((item) => item.id), index, 1), version: categories.data!.version })}>Move down</button></div>}><p>{category.description}</p><div className="menu-items">{itemQueries[index]?.data?.items.map((item, itemIndex, siblings) => <article key={item.id}><div><h3>{item.name}</h3><p>{item.description}</p></div><div className="menu-item-meta"><strong>{formatMoney(item.basePrice)}</strong><Status value={item.available ? 'AVAILABLE' : 'UNAVAILABLE'} /><div className="ops-row-actions"><button onClick={() => void beginItemEdit(item)}>Edit item</button><button disabled={itemIndex === 0} onClick={() => reorderItems.mutate({ category: category.id, ids: move(siblings.map((entry) => entry.id), itemIndex, -1), version: itemQueries[index].data!.version })}>↑</button><button aria-label={`Move ${item.name} down`} disabled={itemIndex === siblings.length - 1} onClick={() => reorderItems.mutate({ category: category.id, ids: move(siblings.map((entry) => entry.id), itemIndex, 1), version: itemQueries[index].data!.version })}>↓</button></div></div></article>) ?? <p>Loading items…</p>}</div></Panel>)}</div>
    <BranchOverrides />
  </>
}

function BranchOverrides() {
  const { selected } = useRestaurantContext()
  const client = useQueryClient()
  const [branchId, setBranchId] = useState(selected.branches[0]?.branchId ?? '')
  const effective = useQuery({ queryKey: queryKeys.branchOverrides(selected.restaurantId, branchId), queryFn: () => restaurantOperationsApi.effectiveItems(selected.restaurantId, branchId), enabled: Boolean(branchId) })
  const [editing, setEditing] = useState<{ id: string; price: string; available: string; version: number } | null>(null)
  const save = useMutation({ mutationFn: () => restaurantOperationsApi.setOverride(selected.restaurantId, branchId, editing!.id, { price: editing!.price || null, available: editing!.available === '' ? null : editing!.available === 'true', version: editing!.version }), onSuccess: () => { setEditing(null); void client.invalidateQueries({ queryKey: queryKeys.branchOverrides(selected.restaurantId, branchId) }) }, onError: (error) => { if ((error as { status?: number }).status === 409) void effective.refetch() } })
  const remove = useMutation({ mutationFn: ({ id, version }: { id: string; version: number }) => restaurantOperationsApi.removeOverride(selected.restaurantId, branchId, id, version), onSuccess: () => void client.invalidateQueries({ queryKey: queryKeys.branchOverrides(selected.restaurantId, branchId) }) })
  return <Panel title="Branch overrides" actions={<select aria-label="Override branch" value={branchId} onChange={(event) => setBranchId(event.target.value)}>{selected.branches.map((branch) => <option key={branch.branchId} value={branch.branchId}>{branch.branchName}</option>)}</select>}>
    <p className="panel-intro">Defaults and branch overrides are shown separately. Reset uses the backend remove-override endpoint.</p>
    <div className="menu-items">{effective.data?.items.map((item) => <article key={item.id}><div><h3>{item.name}</h3><p>Restaurant default: {formatMoney(item.basePrice)} · {item.available ? 'available' : 'unavailable'}</p><p>Branch override: {item.priceOverride == null ? 'No price override' : formatMoney(item.priceOverride)} · {item.availabilityOverride == null ? 'No availability override' : item.availabilityOverride ? 'available' : 'unavailable'}</p></div><div><strong>Effective: {formatMoney(item.effectivePrice)}</strong><div className="ops-row-actions"><button onClick={() => setEditing({ id: item.id, price: item.priceOverride ?? '', available: item.availabilityOverride == null ? '' : String(item.availabilityOverride), version: effective.data.version })}>Edit override</button>{(item.priceOverride != null || item.availabilityOverride != null) && <button onClick={() => remove.mutate({ id: item.id, version: effective.data.version })}>Reset</button>}</div></div></article>)}</div>
    {editing && <form className="inline-editor" onSubmit={(event) => { event.preventDefault(); save.mutate() }}><label>Branch price (EGP)<input inputMode="decimal" value={editing.price} onChange={(event) => setEditing({ ...editing, price: event.target.value })} /></label><label>Branch availability<select value={editing.available} onChange={(event) => setEditing({ ...editing, available: event.target.value })}><option value="">Use default</option><option value="true">Available</option><option value="false">Unavailable</option></select></label><MutationMessage error={save.error} /><button className="primary-button">Save override</button><button type="button" onClick={() => setEditing(null)}>Cancel</button></form>}
  </Panel>
}
