package com.tayyar.notification;

public enum NotificationType {
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    ORDER_PREPARING,
    ORDER_READY_FOR_PICKUP,
    ORDER_OUT_FOR_DELIVERY,
    ORDER_DELIVERED,
    DELIVERY_ASSIGNED,
    RESTAURANT_APPLICATION_APPROVED,
    RESTAURANT_APPLICATION_REJECTED
}
