import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { adminApi } from '../api/admin'
import { ApiError } from '../api/client'
import { queryKeys } from '../api/queryKeys'
import { Empty, Loading, Message, PageHeader, Pager, ReasonDialog, Status, conflictMessage, formatDateTime } from './shared'

export function AdminApplicationsPage() {
  const [status, setStatus] = useState('PENDING'); const [page, setPage] = useState(0)
  const query = useQuery({ queryKey: queryKeys.adminApplications(status, page), queryFn: () => adminApi.applications(status, page), retry: false })
  return <><PageHeader title="Restaurant applications" description="Versioned approval and rejection through the existing ownership workflow." /><div className="admin-filters"><label>Application status<select value={status} onChange={(e) => { setStatus(e.target.value); setPage(0) }}><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select></label></div>{query.isPending ? <Loading /> : query.isError ? <Message>{conflictMessage(query.error, 'Applications could not be loaded.')}</Message> : <><div className="admin-card-grid">{query.data.items.map((application) => <article className="admin-list-card" key={application.id}><Status value={application.status} /><h2>{application.name}</h2><p>{application.description}</p><small>Revision {application.revision} · {formatDateTime(application.updatedAt)}</small><Link to={`/admin/applications/${application.id}`}>Review details</Link></article>)}</div>{!query.data.items.length && <Empty />}<Pager page={query.data.page} size={query.data.size} total={query.data.total} onPage={setPage} /></>}</>
}

export function AdminApplicationPage() {
  const { applicationId = '' } = useParams(); const client = useQueryClient(); const [submissionPage, setSubmissionPage] = useState(0); const [decisionPage, setDecisionPage] = useState(0); const [action, setAction] = useState<'APPROVED' | 'REJECTED' | null>(null); const [message, setMessage] = useState<string | null>(null)
  const application = useQuery({ queryKey: queryKeys.adminApplication(applicationId), queryFn: () => adminApi.application(applicationId), retry: false })
  const submissions = useQuery({ queryKey: queryKeys.adminApplicationSubmissions(applicationId, submissionPage), queryFn: () => adminApi.applicationSubmissions(applicationId, submissionPage), retry: false })
  const decisions = useQuery({ queryKey: queryKeys.adminApplicationDecisions(applicationId, decisionPage), queryFn: () => adminApi.applicationDecisions(applicationId, decisionPage), retry: false })
  const mutation = useMutation({ mutationFn: (reason: string) => adminApi.decideApplication(applicationId, action!, application.data!.version, reason), onSuccess: async () => { setAction(null); setMessage('Application decision recorded after server confirmation.'); await Promise.all([client.refetchQueries({ queryKey: queryKeys.adminApplication(applicationId) }), client.invalidateQueries({ queryKey: ['admin', 'applications', 'list'] }), client.invalidateQueries({ queryKey: queryKeys.adminApplicationDecisions(applicationId, decisionPage) })]) }, onError: async (error) => { if (error instanceof ApiError && error.status === 409) await client.refetchQueries({ queryKey: queryKeys.adminApplication(applicationId) }); setAction(null); setMessage(conflictMessage(error, 'Application decision could not be recorded.')) } })
  if (application.isPending) return <Loading label="Loading application…" />
  if (application.isError) return <Message>{conflictMessage(application.error, 'Application could not be loaded.')}</Message>
  const item = application.data
  return <><Link className="admin-back" to="/admin/applications">← Applications</Link><PageHeader title={item.name} description={`Revision ${item.revision} · applicant ${item.applicantId}`} actions={item.status === 'PENDING' && <><button className="admin-primary" onClick={() => setAction('APPROVED')}>Approve</button><button className="admin-danger" onClick={() => setAction('REJECTED')}>Reject</button></>} />{message && <Message>{message}</Message>}<section className="admin-detail"><Status value={item.status} /><p>{item.description}</p><dl><div><dt>Version</dt><dd>{item.version}</dd></div><div><dt>Submitted</dt><dd>{formatDateTime(item.createdAt)}</dd></div>{item.restaurantId && <div><dt>Restaurant ID</dt><dd className="admin-mono">{item.restaurantId}</dd></div>}</dl></section><History title="Submission history" query={submissions} page={submissionPage} onPage={setSubmissionPage} render={(entry) => <article><strong>Revision {entry.revision}: {entry.name}</strong><p>{entry.description}</p><small>{formatDateTime(entry.submittedAt)}</small></article>} /><History title="Decision history" query={decisions} page={decisionPage} onPage={setDecisionPage} render={(entry) => <article><Status value={entry.outcome} /><strong>Revision {entry.revision}</strong><p>{entry.reason || 'No reason provided.'}</p><small>{formatDateTime(entry.decidedAt)} · reviewer {entry.reviewerId}</small></article>} />{action && <ReasonDialog title={`${action === 'APPROVED' ? 'Approve' : 'Reject'} this application?`} description={action === 'APPROVED' ? 'Approval creates the Restaurant and grants the established owner role.' : 'Rejection requires a reason and does not grant a role.'} confirmLabel={action === 'APPROVED' ? 'Approve application' : 'Reject application'} pending={mutation.isPending} required={action === 'REJECTED'} onCancel={() => setAction(null)} onConfirm={(reason) => mutation.mutate(reason)} />}</>
}

function History<T>({ title, query, page, onPage, render }: { title: string; query: { isPending: boolean; isError: boolean; data?: { items: T[]; page: number; size: number; total: number } }; page: number; onPage: (page: number) => void; render: (item: T) => React.ReactNode }) { return <section className="admin-section"><h2>{title}</h2>{query.isPending ? <Loading /> : query.isError || !query.data ? <Message>History could not be loaded.</Message> : <><div className="admin-timeline">{query.data.items.map((item, index) => <div key={index}>{render(item)}</div>)}</div>{!query.data.items.length && <Empty>No history returned.</Empty>}<Pager page={page} size={query.data.size} total={query.data.total} onPage={onPage} /></>}</section> }
