import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { adminApi } from '../api/admin'
import { queryKeys } from '../api/queryKeys'
import { formatMoney } from '../utils/money'
import { Empty, Loading, Message, PageHeader, Pager, Status, conflictMessage, formatDateTime, shortId } from './shared'

const statuses = ['', 'PENDING_PAYMENT', 'PLACED', 'ACCEPTED', 'PREPARING', 'READY_FOR_PICKUP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'PAYMENT_FAILED', 'REJECTED', 'CANCELLED']
export function AdminOrdersPage() {
  const [draft, setDraft] = useState({ status: '', restaurantId: '', branchId: '', customerId: '' }); const [filters, setFilters] = useState({ ...draft, page: 0 })
  const query = useQuery({ queryKey: queryKeys.adminOrders(filters), queryFn: () => adminApi.orders(filters), retry: false })
  return <><PageHeader title="Order support" description="Read-only historical, payment, delivery, and assignment snapshots." /><form className="admin-filters admin-filters--orders" onSubmit={(e) => { e.preventDefault(); setFilters({ ...draft, page: 0 }) }}><label>Status<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value })}>{statuses.map((status) => <option key={status} value={status}>{status ? status.replaceAll('_', ' ') : 'Any status'}</option>)}</select></label>{(['restaurantId', 'branchId', 'customerId'] as const).map((key) => <label key={key}>{key === 'restaurantId' ? 'Restaurant ID' : key === 'branchId' ? 'Branch ID' : 'Customer ID'}<input value={draft[key]} onChange={(e) => setDraft({ ...draft, [key]: e.target.value.trim() })} /></label>)}<button>Search orders</button></form>{query.isPending ? <Loading /> : query.isError ? <Message>{conflictMessage(query.error, 'Order search failed.')}</Message> : <><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Restaurant</th><th>Status</th><th>Payment</th><th>Total</th><th /></tr></thead><tbody>{query.data.items.map((order) => <tr key={order.id}><td data-label="Order"><strong>{shortId(order.id)}</strong><small>{formatDateTime(order.createdAt)}</small></td><td data-label="Restaurant"><strong>{order.restaurantName}</strong><small>{order.branchName}</small></td><td data-label="Status"><Status value={order.status} /></td><td data-label="Payment">{order.payment ? `${order.payment.method} · ${order.payment.status}` : 'Not available'}</td><td data-label="Total">{formatMoney(order.finalTotal, order.currency)}</td><td><Link className="admin-row-link" to={`/admin/orders/${order.id}`}>Open</Link></td></tr>)}</tbody></table></div>{!query.data.items.length && <Empty />}<Pager page={query.data.page} size={query.data.size} total={query.data.total} onPage={(page) => setFilters({ ...filters, page })} /></>}</>
}

export function AdminOrderPage() {
  const { orderId = '' } = useParams(); const query = useQuery({ queryKey: queryKeys.adminOrder(orderId), queryFn: () => adminApi.order(orderId), retry: false })
  if (query.isPending) return <Loading label="Loading order support detail…" />
  if (query.isError) return <Message>{conflictMessage(query.error, 'Order detail could not be loaded.')}</Message>
  const { order, items, deliveryAddress, history } = query.data
  return <><Link className="admin-back" to="/admin/orders">← Orders</Link><PageHeader title={`Order ${shortId(order.id)}`} description="Read-only support view. No order or payment mutation is available here." /><section className="admin-detail"><dl><div><dt>Status</dt><dd><Status value={order.status} /></dd></div><div><dt>Version</dt><dd>{order.version}</dd></div><div><dt>Restaurant</dt><dd>{order.restaurantName} · {order.branchName}</dd></div><div><dt>Customer ID</dt><dd className="admin-mono">{order.customerId}</dd></div><div><dt>Total</dt><dd>{formatMoney(order.finalTotal, order.currency)}</dd></div><div><dt>Payment</dt><dd>{order.payment ? `${order.payment.method} · ${order.payment.status} · ${formatMoney(order.payment.amount, order.payment.currency)}` : 'Not available'}</dd></div><div><dt>Assignment</dt><dd>{order.assignment ? `${order.assignment.status} · Driver ${order.assignment.driverId}` : 'Unassigned'}</dd></div></dl></section><div className="admin-two-column"><section className="admin-section"><h2>Purchased items</h2>{items.map((item, index) => <article className="admin-line" key={`${item.name}-${index}`}><div><strong>{item.name}</strong><small>{item.quantity} × {formatMoney(item.unitPrice, order.currency)}</small></div><span>{formatMoney(item.lineSubtotal, order.currency)}</span></article>)}{!items.length && <Empty>No item snapshots returned.</Empty>}</section><section className="admin-section"><h2>Delivery address snapshot</h2>{deliveryAddress ? <address>{[deliveryAddress.label, deliveryAddress.street, `Building ${deliveryAddress.building}`, deliveryAddress.floor && `Floor ${deliveryAddress.floor}`, deliveryAddress.apartment && `Apartment ${deliveryAddress.apartment}`, deliveryAddress.city, deliveryAddress.region, deliveryAddress.postalCode, deliveryAddress.countryCode].filter(Boolean).join(' · ')}{deliveryAddress.landmark && <><br />Landmark: {deliveryAddress.landmark}</>}{deliveryAddress.instructions && <><br />Instructions: {deliveryAddress.instructions}</>}</address> : <Empty>No delivery address returned.</Empty>}</section></div><section className="admin-section"><h2>Status history</h2><div className="admin-timeline">{history.map((entry, index) => <article key={`${entry.occurredAt}-${index}`}><Status value={entry.newStatus} /><strong>{entry.previousStatus ? `${entry.previousStatus} → ` : ''}{entry.newStatus}</strong><p>{entry.reason || 'No reason returned.'}</p><small>{formatDateTime(entry.occurredAt)} · {entry.actorKind}{entry.actorId ? ` ${entry.actorId}` : ''}</small></article>)}</div></section></>
}
