import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { adminApi } from '../api/admin'
import { ApiError } from '../api/client'
import { queryKeys } from '../api/queryKeys'
import { Empty, Loading, Message, PageHeader, Pager, ReasonDialog, Status, conflictMessage, formatDateTime } from './shared'

export function AdminRestaurantsPage() {
  const [status, setStatus] = useState(''); const [page, setPage] = useState(0); const filters = { status, page }
  const query = useQuery({ queryKey: queryKeys.adminRestaurants(filters), queryFn: () => adminApi.restaurants(filters), retry: false })
  return <><PageHeader title="Restaurant support" description="Operational status and branch visibility without owner-side editing." /><div className="admin-filters"><label>Status<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(0) }}><option value="">Any status</option><option>ACTIVE</option><option>SUSPENDED</option></select></label></div>{query.isPending ? <Loading /> : query.isError ? <Message>{conflictMessage(query.error, 'Restaurants could not be loaded.')}</Message> : <><div className="admin-card-grid">{query.data.items.map((restaurant) => <article className="admin-list-card" key={restaurant.id}><div><Status value={restaurant.status} /><h2>{restaurant.name}</h2><p>{restaurant.description}</p></div><Link to={`/admin/restaurants/${restaurant.id}`}>Open details</Link></article>)}</div>{!query.data.items.length && <Empty />}<Pager page={query.data.page} size={query.data.size} total={query.data.total} onPage={setPage} /></>}</>
}

export function AdminRestaurantPage() {
  const { restaurantId = '' } = useParams(); const client = useQueryClient(); const [historyPage, setHistoryPage] = useState(0); const [confirming, setConfirming] = useState(false); const [message, setMessage] = useState<string | null>(null)
  const query = useQuery({ queryKey: queryKeys.adminRestaurant(restaurantId), queryFn: () => adminApi.restaurant(restaurantId), retry: false })
  const history = useQuery({ queryKey: queryKeys.adminRestaurantHistory(restaurantId, historyPage), queryFn: () => adminApi.restaurantHistory(restaurantId, historyPage), retry: false })
  const mutation = useMutation({ mutationFn: (reason: string) => adminApi.restaurantStatus(restaurantId, query.data!.status === 'ACTIVE' ? 'SUSPENDED' : 'ACTIVE', query.data!.version, reason), onSuccess: async () => { setConfirming(false); setMessage('Restaurant status updated after server confirmation.'); await Promise.all([client.refetchQueries({ queryKey: queryKeys.adminRestaurant(restaurantId) }), client.invalidateQueries({ queryKey: ['admin', 'restaurants', 'list'] }), client.invalidateQueries({ queryKey: queryKeys.adminRestaurantHistory(restaurantId, historyPage) })]) }, onError: async (error) => { if (error instanceof ApiError && error.status === 409) await client.refetchQueries({ queryKey: queryKeys.adminRestaurant(restaurantId) }); setConfirming(false); setMessage(conflictMessage(error, 'Restaurant status could not be changed.')) } })
  if (query.isPending) return <Loading label="Loading restaurant detail…" />
  if (query.isError) return <Message>{conflictMessage(query.error, 'Restaurant detail could not be loaded.')}</Message>
  const restaurant = query.data
  return <><Link className="admin-back" to="/admin/restaurants">← Restaurants</Link><PageHeader title={restaurant.name} description={restaurant.description} actions={<button className={restaurant.status === 'ACTIVE' ? 'admin-danger' : 'admin-primary'} onClick={() => { setMessage(null); setConfirming(true) }}>{restaurant.status === 'ACTIVE' ? 'Suspend restaurant' : 'Reactivate restaurant'}</button>} />{message && <Message>{message}</Message>}<section className="admin-detail"><dl><div><dt>Status</dt><dd><Status value={restaurant.status} /></dd></div><div><dt>Version</dt><dd>{restaurant.version}</dd></div><div><dt>Created</dt><dd>{formatDateTime(restaurant.createdAt)}</dd></div><div><dt>Updated</dt><dd>{formatDateTime(restaurant.updatedAt)}</dd></div></dl></section><section className="admin-section"><h2>Branches</h2><div className="admin-card-grid">{restaurant.branches.map((branch) => <article className="admin-list-card" key={branch.id}><Status value={branch.paused ? 'PAUSED' : branch.status} /><h3>{branch.name}</h3><p>{branch.city}</p><small className="admin-mono">{branch.id}</small></article>)}</div>{!restaurant.branches.length && <Empty>No branches returned.</Empty>}</section><section className="admin-section"><h2>Status history</h2>{history.isPending ? <Loading /> : history.isError ? <Message>History could not be loaded.</Message> : <><div className="admin-timeline">{history.data.items.map((item) => <article key={item.id}><Status value={item.newStatus} /><strong>{item.previousStatus} → {item.newStatus}</strong><p>{item.reason}</p><small>{formatDateTime(item.changedAt)} · actor {item.actorId}</small></article>)}</div>{!history.data.items.length && <Empty>No status changes recorded.</Empty>}<Pager page={history.data.page} size={history.data.size} total={history.data.total} onPage={setHistoryPage} /></>}</section>{confirming && <ReasonDialog title={`${restaurant.status === 'ACTIVE' ? 'Suspend' : 'Reactivate'} this restaurant?`} description="This affects platform availability. The current server version will be checked before the status changes." confirmLabel={restaurant.status === 'ACTIVE' ? 'Suspend restaurant' : 'Reactivate restaurant'} pending={mutation.isPending} onCancel={() => setConfirming(false)} onConfirm={(reason) => mutation.mutate(reason)} />}</>
}
