import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { adminApi } from '../api/admin'
import { ApiError } from '../api/client'
import { queryKeys } from '../api/queryKeys'
import { Empty, Loading, Message, PageHeader, Pager, ReasonDialog, Status, conflictMessage, formatDateTime, shortId } from './shared'

const roles = ['', 'CUSTOMER', 'RESTAURANT_OWNER', 'RESTAURANT_STAFF', 'DRIVER', 'ADMIN']
export function AdminUsersPage() {
  const [draft, setDraft] = useState({ email: '', status: '', role: '' }); const [filters, setFilters] = useState({ ...draft, page: 0 })
  const query = useQuery({ queryKey: queryKeys.adminUsers(filters), queryFn: () => adminApi.users(filters), retry: false })
  return <><PageHeader title="User support" description="Exact-email search with server-side status and role filtering." /><form className="admin-filters" onSubmit={(event) => { event.preventDefault(); setFilters({ ...draft, email: draft.email.trim().toLowerCase(), page: 0 }) }}><label>Email<input type="email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} placeholder="user@example.com" /></label><label>Status<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value })}><option value="">Any status</option><option>ACTIVE</option><option>SUSPENDED</option></select></label><label>Role<select value={draft.role} onChange={(e) => setDraft({ ...draft, role: e.target.value })}>{roles.map((role) => <option key={role} value={role}>{role ? role.replaceAll('_', ' ') : 'Any role'}</option>)}</select></label><button>Search users</button></form>{query.isPending ? <Loading /> : query.isError ? <Message>{conflictMessage(query.error, 'User search failed. Try again.')}</Message> : <><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Roles</th><th>Status</th><th>Created</th><th /></tr></thead><tbody>{query.data.items.map((user) => <tr key={user.id}><td data-label="User"><strong>{user.fullName}</strong><small>{user.email}</small></td><td data-label="Roles">{user.roles.map((role) => <span className="admin-chip" key={role}>{role.replaceAll('_', ' ')}</span>)}</td><td data-label="Status"><Status value={user.status} /></td><td data-label="Created">{formatDateTime(user.createdAt)}</td><td><Link className="admin-row-link" to={`/admin/users/${user.id}`} aria-label={`Open support details for ${user.fullName}`}>Open</Link></td></tr>)}</tbody></table></div>{!query.data.items.length && <Empty /> }<Pager page={query.data.page} size={query.data.size} total={query.data.total} onPage={(page) => setFilters({ ...filters, page })} /></>}</>
}

export function AdminUserPage() {
  const { userId = '' } = useParams(); const client = useQueryClient(); const [action, setAction] = useState<'suspension' | 'reactivation' | null>(null); const [message, setMessage] = useState<string | null>(null)
  const query = useQuery({ queryKey: queryKeys.adminUser(userId), queryFn: () => adminApi.user(userId), retry: false })
  const mutation = useMutation({ mutationFn: (reason: string) => adminApi.accountStatus(userId, action!, reason), onSuccess: async (user) => { client.setQueryData(queryKeys.adminUser(userId), user); setAction(null); setMessage(`Account ${user.status === 'ACTIVE' ? 'reactivated' : 'suspended'} after server confirmation.`); await Promise.all([client.invalidateQueries({ queryKey: ['admin', 'users', 'list'] }), client.invalidateQueries({ queryKey: ['admin', 'audit', 'list'] })]) }, onError: async (error) => { if (error instanceof ApiError && error.status === 409) await client.refetchQueries({ queryKey: queryKeys.adminUser(userId) }); setAction(null); setMessage(conflictMessage(error, 'The account state could not be changed.')) } })
  if (query.isPending) return <Loading label="Loading user detail…" />
  if (query.isError) return <Message>{conflictMessage(query.error, 'User detail could not be loaded.')}</Message>
  const user = query.data
  return <><Link className="admin-back" to="/admin/users">← Users</Link><PageHeader title={user.fullName} description={`User ${shortId(user.id)} · safe support profile`} actions={<button className={user.status === 'ACTIVE' ? 'admin-danger' : 'admin-primary'} onClick={() => { setMessage(null); setAction(user.status === 'ACTIVE' ? 'suspension' : 'reactivation') }}>{user.status === 'ACTIVE' ? 'Suspend account' : 'Reactivate account'}</button>} />{message && <Message success={!message.toLowerCase().includes('could') && !message.toLowerCase().includes('cannot')}>{message}</Message>}<section className="admin-detail"><dl><div><dt>Email</dt><dd>{user.email}</dd></div><div><dt>Status</dt><dd><Status value={user.status} /></dd></div><div><dt>Roles</dt><dd>{user.roles.map((role) => <span className="admin-chip" key={role}>{role.replaceAll('_', ' ')}</span>)}</dd></div><div><dt>Created</dt><dd>{formatDateTime(user.createdAt)}</dd></div><div><dt>Last updated</dt><dd>{formatDateTime(user.updatedAt)}</dd></div><div><dt>User ID</dt><dd className="admin-mono">{user.id}</dd></div></dl></section>{action && <ReasonDialog title={action === 'suspension' ? 'Suspend this account?' : 'Reactivate this account?'} description="The server will validate account state and safety constraints before making any change." confirmLabel={action === 'suspension' ? 'Suspend account' : 'Reactivate account'} pending={mutation.isPending} onCancel={() => setAction(null)} onConfirm={(reason) => mutation.mutate(reason)} />}</>
}
